### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by SyedWasiHaider** [lrembacz/vue-responsive-grid-layout#1]
Hi there

I want to thank you for taking the effort to make this. There is currently no other Vue grid library that is both responsive, draggable/resizable. Most involve using gridstack or jquery or vue-grid-layout (which is not responsive).

Please add a demo so people can see that this works well.

EDIT: Actually I notice you have an example folder. If you could just host that and let people click on it to play, that would be nice. You can use something like surge.sh which is free hosting.

**Comment by lrembacz** [comment]
Hi there! 

You can actually clone this repo on your local machine then type `npm install` & `npm run dev` to try this out! Its making webpack server for you on port :8080.

I'm planning to host it or make jsfiddle version, but still trying this and making fixes. 

Thanks for your words!

**Comment by lrembacz** [comment]
Demo has been added to readme.md file.
