### ISSUE TITLE
Nuxt.js support

### ISSUE THREAD

**Issue by PlainBane** [lrembacz/vue-responsive-grid-layout#12]
Hi, 
Is there a way to get this working with Nuxt.js? I tried to run it as plugin with SSR false, but it can't find the window.

**Comment by lrembacz** [comment]
I was trying to make it possible but there are some issues with inject / provide I guess. I'll try to fix this and make it Nuxt.js supported. If u know what should I change to make it possible, just give me an advice or feel free to make a PR.

Thanks!

**Comment by PlainBane** [comment]
Ok, I'll take a look at it. Maybe I can come up with something.

**Comment by robsontenorio** [comment]
Have you tried to wrap it with `<no-ssr>` tag?

**Comment by lrembacz** [comment]
It will be possible in next version probably https://github.com/lrembacz/vue-responsive-grid-layout/pull/41.
