### ISSUE TITLE
Allow resize from any corner

### ISSUE THREAD

**Issue by robsontenorio** [lrembacz/vue-responsive-grid-layout#18]
Sometimes when you have large content it is easy to resize it from top right corner instead of bottom right corner. 

Right bottom resizing causes some glitches with large content.

**Comment by lrembacz** [comment]
Yes, I'm working on this for new version of VueResponsiveGridLayout 2.x. 
Maybe it will be merged in this old version as well.

A little problem with resizing from any corner is fact that the element should change it position simultaneously when being resized.

**Comment by robsontenorio** [comment]
Maybe you consider in this next version allow user to choose one corner. Something “top-right” , “bottom-right”.  Simple than to allow from any corner.

**Comment by lrembacz** [comment]
It will be partly possible in next version https://github.com/lrembacz/vue-responsive-grid-layout/pull/41.
