### ISSUE TITLE
Vertical resizing doesn't work

### ISSUE THREAD

**Issue by ayZagen** [lrembacz/vue-responsive-grid-layout#2]
Vertical resizing in your example doesn't work as expected

**Comment by lrembacz** [comment]
What do you actually mean?
It works for me as it should.

**Comment by ayZagen** [comment]
I cant resize vertically. resize handler moves but component itself doesn't resize

**Comment by lrembacz** [comment]
In my example there is `heightFromChildren` prop set to true. Which means that height of `grid-item` is strictly taken from component wrapped there. And cannot be more or less. Its working like https://packery.metafizzy.co/, so only width is taken from my grid-layout options.

If u want to use it in normal mode please set this prop to false or just delete it.

Additionally you will need to make some changes to component wrapped inside, and change its css styles to make the height 100% which will grant you, your wanted case. Now this element is flexbox which height is based on content.
