### ISSUE TITLE
Drag to starting position does not display

### ISSUE THREAD

**Issue by emcho92** [lrembacz/vue-responsive-grid-layout#21]
When dragging an item from a certain position, it does not allow you to put it back in the same exact position again. This seems to be by design now, however it is pretty weird. If I pick up a draggable item from the coordinates x: 1, y: 1, I would assume I can put it back on those same coordinates if I changed my mind on moving it to another position. Take a look at the GIF below, this is a clip of the demo.

![recording](https://user-images.githubusercontent.com/3452320/57556363-1e68d500-7377-11e9-8a17-5954c38ee18f.gif)

Tracked this issue down to this: https://github.com/lrembacz/vue-responsive-grid-layout/blob/b53a61a35624a0218f9d127fc3b789d96d9bf86c/src/components/VueGridLayout.vue#L344

Removing the layout comparison fixes it.

Also I think it would be good to highlight in the docs that `position: relative` is very important, to put on the direct parent of the resizable container, otherwise drag positions are not calculated properly. Like in the demo when you pick up/start dragging an item, it jumps downwards, because of the offset parent is not the direct parent but the top most parent which calculates in the navbar in the demo.

Another unrelated thing. The demo is a bit messy. There's the whole `example-component` there which is not used anywhere.

Let me know if you want me to make a PR for some of these changes, even doc wise, I can help out when I find time. All in all, thanks for the nice lib.

**Comment by lrembacz** [comment]
Thanks for your help. I will try to fix it in the coming days.

**Comment by tripflex** [comment]
I can confirm this as well, and only happens when you have not dropped it.

@emcho92 i'm sure @lrembacz would be happy for any PRs for docs, examples, or anything else that could help with the project 👍 

If I start using this (which i may now based on my issues with `vue-grid-layout`) I will try to help out as well (just need to figure out how difficult it will be to convert over from `vue-grid-layout`)

**Comment by tripflex** [comment]
With that said, here's a codesandbox.io version of the demo:
https://codesandbox.io/s/vue-responsive-grid-demo-fh2e9?fontsize=14&module=%2Fsrc%2FApp.vue

I'll probably be using this to fork and test out different features/bugs/issues moving forward

**Comment by lrembacz** [comment]
It is fixed check https://jsfiddle.net/pebwnfL8/.
