### ISSUE TITLE
Prevent static items from moving

### ISSUE THREAD

**Issue by notchris** [lrembacz/vue-responsive-grid-layout#22]
I'm unable to prevent an item from moving using the static property. Has this been fixed in latest?

**Comment by lrembacz** [comment]
https://github.com/lrembacz/vue-responsive-grid-layout/blob/master/src/lib/utils.ts#L402

Yes, as I can see it should work.

https://jsfiddle.net/n2hxrwe1/

Just add immobile prop to your grid item.
