### ISSUE TITLE
Custom grid (different column width)

### ISSUE THREAD

**Issue by kosirm** [lrembacz/vue-responsive-grid-layout#23]
Hi, this is really a great project, thank you for sharing code!!! I would like to use this project for golden ratio grid layout, which I'm using for my project. Here is [a simple example](https://grid.layoutit.com/?id=8W7Qrgy) of golden ratio grid, implemented with css grid. How would be possible to create custom grid (different column width) in vue-responsive-grid-layout?  I would like to pass **object** with different column width for every column to cols variable in vue-responsive-grid-layout (instead of number). Do you think this would be possible to implement with this project?

**Comment by lrembacz** [comment]
It's not possible to define custom width in current version of vue-responsive-grid-layout. You can only define your width as cols recomended and tested is just 12 columns for view. If you want you can fork this repo and try to change it the way you want.
