### ISSUE TITLE
Smooth Animations when Dragging and Resizing

### ISSUE THREAD

**Issue by ico85** [lrembacz/vue-responsive-grid-layout#33]
Is there a way to make smooth Animations like in react-grid-layout when you drag or resize an item?

**Comment by lrembacz** [comment]
@ico85 Yes. You need only provide custom CSS transitions for you needs.

Just like in react-grid-layout. https://github.com/STRML/react-grid-layout/blob/master/css/styles.css

For example:
https://jsfiddle.net/os58d0bt/
