### ISSUE TITLE
Endless loop and crash after VueGridItem removal

### ISSUE THREAD

**Issue by sdennler** [lrembacz/vue-responsive-grid-layout#35]
Hello and thanks for the great libary!

I run into a issue when using it which leads to a endless loop and a unresponsable browser tab. As I'm new to vue.js, there is a good change I just do it the wrong way however.

The issue happens after a VueGridItem is removed during runtime and a new one is added:

> [Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

This happens regardless of that the VueGridItem have unique id's.

Here is a jsfiddle based on the demo who shows this issue: https://jsfiddle.net/so6ch0vr/

As a additional question: How to make a button on the VueGridItem? I could not make them clickable as the dragging starts before the button is clicked...

Thanks for looking into this and any help!

**Comment by lrembacz** [comment]
@sdennler You were using old version from dev branch.
If you want to use button on draggable component you need to add `cancel` prop with querySelector on that.
 Ive updated ur xample https://jsfiddle.net/cv2p53ha/.

**Comment by sdennler** [comment]
Great! Thanks a lot for your help!
