### ISSUE TITLE
The drag start position calculates incorrectly when the grid is offset from the top of the browser window

### ISSUE THREAD

**Issue by anders-rv** [lrembacz/vue-responsive-grid-layout#4]
Hi,

Thank you for creating this component -- it seems to be an almost perfect fit for something I'm trying to prototype.

I noticed that the onDragStart handler appears to calculate the position incorrectly of the dragged outline incorrectly when the grid is offset from the top-left of the window, probably indicated by this comment:

_// TODO: this wont work on nested parents_

This would be a good thing to fix I think.

Thanks!

**Comment by lrembacz** [comment]
Yes. I know this issue. I'll try to fix it in free time, maybe next week. If you have an idea about solution you can help me or just submit PR. Thanks :)

**Comment by lrembacz** [comment]
Issue has been solved. Check new version + demo.

**Comment by anders-rv** [comment]
Thanks for the update to this!

I still couldn't get it to work right (with _useCSSTransforms_ enabled at least) and the problem can easily be reproduced by simply putting some text before the app in index.html which causes the jumps-on-drag to appear.

I was able to fix the offset calculation by removing the references to _parentRect.top_/left from VueGridItem _onDragStart_, but I wasn't entirely sure if that is a complete fix.

Thanks!

**Comment by lrembacz** [comment]
Thanks fro info!

I returned to the previous version due to this issue. And added styles to `vue-responsive-grid-layout`. And now it works correctly I guess. Please update your version and check demo.

**Comment by anders-rv** [comment]
I think that fixed it -- everything seems to work perfect now.

Awesome, much appreciated!

**Comment by lrembacz** [comment]
No problem! :) Nice to read that :D

**Comment by Pwntus** [comment]
This issue still kind of persists when **resizing boxes**. I don't know what causes it but I'll explain:

At initial resize, everything is OK. If you drop the box so that it has to adjust its size to fit the grid, the next time you resize the box it will offset from the mouse the previous offset.

[Demo:](https://imgur.com/8ZENLKj)

![demo](https://i.imgur.com/8ZENLKj.gif)

This is also seen in the demos.

**Comment by lrembacz** [comment]
In 2.0 version this is all fixed. Check next branch.
