### ISSUE TITLE
Add this to https://github.com/vuejs/awesome-vue

### ISSUE THREAD

**Issue by SyedWasiHaider** [lrembacz/vue-responsive-grid-layout#5]
I think I'm pretty satisfied with the way this library works at the moment and I think it would be best if it got exposure to more people.

**Comment by SyedWasiHaider** [comment]
I also recommend submitting this to hacker news

**Comment by lrembacz** [comment]
It is not finished yet actually. I'm working to do this layout reactive fully and I need a bit of time to make some promises inside to achieve async calls in one task without calling so many events. It will be easier then for make it compatible with Vuex and different tools.

Thanks for advices :)

**Comment by SyedWasiHaider** [comment]
Great work! I'll close this for now.
