### ISSUE TITLE
Resizing start position incorrect in some cases

### ISSUE THREAD

**Issue by Pwntus** [lrembacz/vue-responsive-grid-layout#7]
At initial resize, everything is OK. If you drop the box so that it has to adjust its size to fit the grid, the next time you resize the box it will offset from the mouse the previous offset.

[Demo:](https://imgur.com/8ZENLKj)

![demo](https://i.imgur.com/8ZENLKj.gif)

This is also seen in the demos.

**Comment by Pwntus** [comment]
### I've tried to track down the origin of this bug.

* [src/utils/utils.js#L1](https://github.com/lrembacz/vue-responsive-grid-layout/blob/master/src/utils/utils.js#L1): `setTransform(_ref2)` gets a "wrong" width property on the `_ref2` parameter.
* [src/VueGridItem.vue#L390](https://github.com/lrembacz/vue-responsive-grid-layout/blob/master/src/VueGridItem.vue#L390): the `createStyle` method is using `utils.setTransform` with a `pos` argument, which in turn it gets as a parameter.
* [src/VueGridItem.vue#L282](https://github.com/lrembacz/vue-responsive-grid-layout/blob/master/src/VueGridItem.vue#L282): the computed variable `styles` is using the `createStyle` method, passing it the `pos` argument created by another method called `calcPosition`.
* [src/VueGridItem.vue#L325](https://github.com/lrembacz/vue-responsive-grid-layout/blob/master/src/VueGridItem.vue#L325): `calcPosition` takes a widget `x, y, w, h` and returns a `top, left, width, height` object used to transform the visible DOM-element. This is where it gets wrong. This method has a if-clause; `if (this.resizing)` where it replaces the width & height by the `this.resizing` variable. In this specific case, when resizing a widget, the `this.resizing` value is a size value derived from an external package, also maintained by you @lrembacz called [vue-resizable-core](https://github.com/lrembacz/vue-resizable-core).

Ultimately, I think there's something wrong in `resizeHandler` for the package `vue-resizable-core` here: [vue-resizable-core/src/VueResizableCore.vue#L172](https://github.com/lrembacz/vue-resizable-core/blob/master/src/VueResizableCore.vue#L172).

Whether the old or the new width / height isn't updated properly I don't know.

**Comment by lrembacz** [comment]
Thanks for your help. 
Yes, I've found the reason for this problem is the resize package and its height / width from the previous size change.
 I will try to fix it and let you know.

**Comment by lrembacz** [comment]
Dev branch is making many changes and I'm about to finish this. There is Vuex + Typescript example and some fixes to the issues. Thanks :)
